### ISSUE TITLE
Which-key not found after fresh install

### ISSUE THREAD

**Issue by jasonpott** [jmbuhr/quarto-nvim-kickstarter#89] opened 2024-03-04 22:40 UTC
Hi  I have been struggling to integrate the quarto settings into a custom lazy config and came across your you tube video so thought I would try to work up my config from your kickstarter. 

I removed my config and removed the local storage for the previous lazy config. I have made no changes to your files at this stage.

After installing the configuration and letting the first setup complete installation of the language servers.  On restart I am getting this error message:

```
Error detected while processing /Users/jason/.config/nvim/init.lua:
Failed to load `plugins.ui`

...0.9.5/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'markdown' language, see :help treesitter-parsers

# stacktrace:
  - /usr/local/Cellar/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter/language.lua:93 _in_ **add**
  - /usr/local/Cellar/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:252 _in_ **parse**
  - ui.lua:233
  - ~/.config/nvim/lua/config/lazy.lua:16
  - ~/.config/nvim/init.lua:2
E5113: Error while calling lua chunk: /Users/jason/.config/nvim/lua/config/keymap.lua:1: module 'which-key' not found:
        no field package.preload['which-key']
cache_loader: module which-key not found
cache_loader_lib: module which-key not found
        no file './which-key.lua'
        no file '/usr/local/share/luajit-2.1/which-key.lua'
        no file '/usr/local/share/lua/5.1/which-key.lua'
        no file '/usr/local/share/lua/5.1/which-key/init.lua'
        no file './which-key.so'
        no file '/usr/local/lib/lua/5.1/which-key.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /Users/jason/.config/nvim/lua/config/keymap.lua:1: in main chunk
        [C]: in function 'require'
        /Users/jason/.config/nvim/init.lua:4: in main chunk
```
and then:

```
Failed to run `init` for **vim-slime**

/Users/jason/.config/nvim/lua/plugins/quarto.lua:628: module 'which-key' not found:
^Ino field package.preload['which-key']
cache_loader: module which-key not found
cache_loader_lib: module which-key not found
^Ino file './which-key.lua'
^Ino file '/usr/local/share/luajit-2.1/which-key.lua'
^Ino file '/usr/local/share/lua/5.1/which-key.lua'
^Ino file '/usr/local/share/lua/5.1/which-key/init.lua'
^Ino file './which-key.so'
^Ino file '/usr/local/lib/lua/5.1/which-key.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - quarto.lua:628 _in_ **init**
  - ~/.config/nvim/lua/config/lazy.lua:16
  - ~/.config/nvim/init.lua:2
```

I have a working installation of quarto but hadn't previously got it configured properly with nvim.

I realised that I hadn't removed the .local state / share from the previous installation so removed those and did a fresh install. But the errors came through again. 

I'm new to nvim so forgive any obvious errors I have made.

**Comment by jasonpott** [comment] 2024-03-04 23:00
Thanks I will take a look at the earlier release.

**Comment by edwintorok** [comment] 2024-03-04 23:14
I haven't debugged why 3.0.0 doesn't work, just came here to report it, and seen that you already have. Good to know it is not a problem with my system. FWIW I have NeoVim 0.9.5 on Fedora39.

**Comment by jmbuhr** [comment] 2024-03-05 07:13
I wasn't able to reproduce this on my machine, but noticed that I had lost calling which-key's setup. Can you confirm if above commit fixes the issue?

**Comment by jmbuhr** [comment] 2024-03-05 07:14
I don't expect version 3 to install slower than 2, since the amount of plugins is about the same. But if you switch between versions you'll have some already installed so the second one will always be faster.

**Comment by jmbuhr** [comment] 2024-03-05 07:31
Ah, no, that was just a symptom from the config not being processed all the way through, because I was using treesitter functionality from nvim version 0.10. While I check for a fix you can use this config with the latest nvim nightly (https://github.com/neovim/neovim/releases/tag/nightly)

**Comment by jmbuhr** [comment] 2024-03-05 07:37
found the problem. Should be fixed now

**Closed** 2024-03-05 07:37 UTC
